name: 'project'
version: '1.0.0'
config-version: 2
profile: 'ecommerce_dbt'
model-paths: ['models']
snapshot-paths: ['snapshots']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']

models:
  project:
    +materialized: table